### ISSUE TITLE
Ostrzeżenie o nieistniejącym zawodniku

### ISSUE THREAD

**Issue by michzimny** [emkael/jfrteamy-ausbutler#3]
Teraz wygląda tak:
```
WARNING: player ID=140 (round 1, segment 1) not in players database
```

Gdyby był jeszcze numer stołu i pokój, to juz wszystko byłoby jasne i nie trzeba byłoby szukać ręcznie :-)

**Comment by emkael** [comment]
Podrzucisz testową bazę z takim nieistniejącym zawodnikiem?

**Comment by michzimny** [comment]
poszło mailem

**Comment by emkael** [comment]
W sumie nie potrzebowałem, nie zauważyłem, że mam te informacje wyciągnięte w zmiennej lokalnej :)
