### ISSUE TITLE
Nieczytelny błąd o brakach w tabeli logoh

### ISSUE THREAD

**Issue by michzimny** [emkael/jfrteamy-ausbutler#4]
Teraz program wypluwa `ERROR: KeyError: 99`, a mógłby może jakoś bardziej opisowo, że tabela logoh jest pusta, czy coś? Bo już pewnie ze trzeci raz się zastanawiam, co ten błąd oznacza :)

**Comment by emkael** [comment]
Wykryję, gdy ten błąd miałby się pojawić i wyświetlę ostrzeżenie. Teraz będzie można albo dodać taki klucz tłumaczeń do pliku konfiguracyjnego ręcznie - i będzie działać albo nie dodawać i w miejscu odpowiedniego napisu wyświetli się `{{KLUCZ_NAPISU}}`.

Może tak być?

**Comment by michzimny** [comment]
Super.
